version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    networks:
      - bridge
    volumes:
      - my-db:/var/lib/postgresql/data

  userapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - bridge

networks:
  bridge: {}

volumes:
  my-db:
